DOC-555 | Release notes for in-memory cache subsystem 3.11.4
arangodb/docs-hugo pull request #217
Opened 2023-09-18 12:03 UTC by nerpaula

### Description

#### Upstream PRs

- 3.10:
- 3.11:
- 3.12:

2023-09-18 22:45 UTC, Simran-B requested changes

2023-09-18 22:45 UTC, Simran-B commented on site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Duplicate entry

2023-09-19 08:24 UTC, nerpaula commented on site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Removed.

2023-09-20 07:46 UTC, Simran-B approved these changes
Updated version remark(s)

2023-09-20 08:21 UTC, merged