fix: Style normalization and beautification
arangodb/docs-hugo pull request #244
Opened 2023-09-27 07:56 UTC by nikhil-varma

### Description

#### Upstream PRs

- 3.10:
- 3.11:
- 3.12:

2023-09-27 11:16 UTC, palashkaria requested changes

2023-09-27 11:16 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme-relearn-light.css
> +    --SECURITY-BORDER-COLOR: #FFA500;
Let's use the var(--orange-400) here

2023-09-27 11:16 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme-relearn-light.css
> +    --INFO-ICON-COLOR: #276f86; /* var(--blue-500);*/
let's keep using the blue variable we have

2023-09-27 11:16 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme-relearn-light.css
> +    --DANGER-ICON-COLOR: #fa8151;
we can keep using the red here

2023-09-27 11:16 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme.css
> +    border-bottom: 0;;
```suggestion
    border-bottom: 0;
```

2023-09-27 11:16 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme.css
> +    background: rgb(240, 240, 240);
this is gray-100

2023-09-27 11:16 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme.css
> +    background: rgb(240, 240, 240);
gray-100

2023-09-27 11:16 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme.css
> +    color: rgb(68, 68, 68);
gray-900

2023-09-27 11:16 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme.css
> +    background: #e3e3e3;
gray-200

2023-09-27 11:16 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme.css
> +    color: #53785c;
green-700

2023-09-27 11:16 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme.css
> +    background: #e3e3e3;
gray-200

2023-09-27 11:24 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme-relearn-light.css
> +    --INFO-ICON-COLOR:  var(--blue-500);
```suggestion
    --INFO-ICON-COLOR: var(--blue-500);
```

2023-09-27 11:24 UTC, palashkaria commented on site/themes/arangodb-docs-theme/static/css/theme.css
> +    margin: 7px;
Lets try to stick to multiples of 4/2

2023-09-27 19:50 UTC, Simran-B commented
The text contrast of inline code is not good, and way too low if it's in a link. The link underline is also not visible below inline code (see "`db` object" link):

<img width="624" alt="image" src="https://github.com/arangodb/docs-hugo/assets/7819991/2df18c1a-8cde-461a-9f15-158a3f32d336">

It doesn't look good and has too little contrast in headlines as well:
<img width="268" alt="image" src="https://github.com/arangodb/docs-hugo/assets/7819991/c81b538e-bf89-4127-a46e-d9af9d290d06">

The copy button overlapping the content is not nice. There would be space to make the code box wider in this case, but to improve it more generally, could we show the copy button only on hover over the code box?

<img width="616" alt="image" src="https://github.com/arangodb/docs-hugo/assets/7819991/a3a33f89-8927-40cb-a40e-e7011e401d54">

Boxes like [here](https://deploy-preview-244--docs-hugo.netlify.app/3.11/develop/http/collections/#get-the-properties-of-a-collection_res_200_cacheEnabled) need to be restyled still. Having the same border radius on nested boxes looks wrong:

<img width="631" alt="image" src="https://github.com/arangodb/docs-hugo/assets/7819991/c6fa9f0b-63ec-4155-bf50-ff4c6bf79e78">

The margin between list items for dense lists seems to be the same as the regular line height.

2023-09-28 08:23 UTC, nikhil-varma commented
@Simran-B 
Links & contrast are fixed already. Will get the inline code sorted.

Any further changes would be a part of a separate ticket. It becomes tricky to handle details. Let's keep the scope as-is for this one. Please use this ticket to write down whatever is necessary for the next set of issues: https://arangodb.atlassian.net/browse/DOC-585

2023-09-29 08:03 UTC, palashkaria approved these changes
LGTM!

2023-09-29 09:19 UTC, merged