Improve error codes reference
arangodb/docs-hugo pull request #253
Opened 2023-09-29 13:15 UTC by Simran-B

### Description

- Use error number for headline anchors instead of full headline text like in Jekyll toolchain, e.g. `#11` instead of `#11---forbidden`.

- Add a description about status/error codes, numbers, messages, and descriptions

- Fix gap in headline levels between h2 and h4

- Wrap very long headlines mid-word if they would overflow, e.g. `4011 - ERROR_UNSUPPORTED_CHANGE_IN_SMART_TO_SATELLITE_DISJOINT_EDGE_DIRECTION`

  This should only affect headlines that contain unusually long words without spaces (like error names) but not wrap mid-word for normal headlines that span multiple lines

#### Upstream PRs

- 3.10:
- 3.11:
- 3.12:

2023-09-29 17:55 UTC, nikhil-varma commented on site/content/3.10/develop/error-codes-and-meanings.md
> +[HTTP REST API](http/_index.md) responds to a request with with an
Double 'with'

```suggestion
[HTTP REST API](http/_index.md) responds to a request with an
```

2023-09-29 18:01 UTC, nikhil-varma requested changes

2023-09-29 18:01 UTC, nikhil-varma commented on site/content/3.11/develop/error-codes-and-meanings.md
> +[HTTP REST API](http/_index.md) responds to a request with with an
Same here.. double 'with'

```suggestion
[HTTP REST API](http/_index.md) responds to a request with an
```

2023-09-29 18:01 UTC, nikhil-varma commented on site/content/3.11/develop/error-codes-and-meanings.md
> +The **error name** is not visible in the HTTP API response. The name for the
Same structural change here as well

2023-09-29 18:01 UTC, nikhil-varma commented on site/content/3.12/develop/error-codes-and-meanings.md
> +[HTTP REST API](http/_index.md) responds to a request with with an
```suggestion
[HTTP REST API](http/_index.md) responds to a request with an
```

2023-09-29 18:01 UTC, nikhil-varma commented on site/content/3.12/develop/error-codes-and-meanings.md
> +The **error name** is not visible in the HTTP API response. The name for the
Same here

2023-09-29 18:02 UTC, nikhil-varma commented
@Simran-B CSS seems fine. Just some suggestions on the content. Please feel free to address it in the best suited approach. Thanks!

2023-09-29 20:22 UTC, Simran-B commented on site/content/3.10/develop/error-codes-and-meanings.md
> +`@arangodb` module maps error names to error numbers:
I did reorder this when writing twice but I think you are right that it's still not great. How about this order?

Error names are used in code to refer to an error kind, in the server's own code as well as in
other code like drivers. For instance, the name for the error with the number 11 is ERROR_FORBIDDEN.
The error name is not visible in the HTTP API response.

In the JavaScript API, ...

2023-10-10 14:42 UTC, nerpaula approved these changes

2023-10-10 16:21 UTC, merged