DOC-614 | Added `readOwnWrites` option for UPSERT operations
arangodb/docs-hugo pull request #409
Opened 2024-01-04 01:45 UTC by nerpaula

### Description

Added `readOwnWrites` option for UPSERT operations.

#### Upstream PRs

- 3.10:
- 3.11:
- 3.12: https://github.com/arangodb/arangodb/pull/20134

2024-01-04 09:28 UTC, Simran-B requested changes

2024-01-04 09:28 UTC, Simran-B commented on site/content/3.12/aql/high-level-operations/upsert.md
> +be guaranteed that the input of the `UPSERT` leads to disjoint documents being
```suggestion
You should only set the `readOwnWrites` option to `false` if you can
guarantee that the input of the `UPSERT` leads to disjoint documents being
```

2024-01-04 09:28 UTC, Simran-B commented on site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
> +The `readOwnWrites` option has been added for `UPSERT` operations. The default
```suggestion
A `readOwnWrites` option has been added for `UPSERT` operations. The default
```

2024-01-04 09:28 UTC, Simran-B commented on site/content/3.12/aql/high-level-operations/upsert.md
> +in batches. A batch has normally 1000 inputs, so it can lead to a faster execution.
```suggestion
in batches. Normally, a batch has 1000 inputs, which can lead to a faster execution.
```

2024-01-04 09:28 UTC, Simran-B commented on site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
> +in batches. A batch has normally 1000 inputs, so it can lead to a faster execution.
```suggestion
in batches. Normally, a batch has 1000 inputs, which can lead to a faster execution.
```

2024-01-04 09:28 UTC, Simran-B commented on site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
> +be guaranteed that the input of the `UPSERT` leads to disjoint documents being
```suggestion
Therefore, you should only set the `readOwnWrites` option to `false` if you can
guarantee that the input of the `UPSERT` leads to disjoint documents being
```

2024-01-04 09:28 UTC, Simran-B commented on site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
> +value is `true`. When set to `true`, an `UPSERT` operation processes its
```suggestion
value is `true` and the behavior is identical to previous versions of ArangoDB that
do not have this option. When enabled, an `UPSERT` operation processes its
```

2024-01-04 10:11 UTC, nerpaula commented on site/content/3.12/aql/high-level-operations/upsert.md
> +However, when using batches, the `UPSERT` operation cannot observe its own writes.
How would you rephrase it?

2024-01-05 17:49 UTC, Simran-B commented on site/content/3.12/aql/high-level-operations/upsert.md
> +However, when using batches, the `UPSERT` operation cannot observe its own writes.
However, when using batches, the `UPSERT` operation can essentially not observe its own writes.

2024-01-05 17:50 UTC, Simran-B commented on site/content/3.12/aql/high-level-operations/upsert.md
> +However, when using batches, the `UPSERT` operation cannot observe its own writes.
```suggestion
However, when using batches, the `UPSERT` operation can essentially not observe its own writes.
```

2024-01-08 12:59 UTC, Simran-B approved these changes

2024-01-08 13:02 UTC, merged