DOC-614 | Remove Pregel
arangodb/docs-hugo pull request #460
Opened 2024-02-07 06:34 UTC by nerpaula

### Description

#### Upstream PRs

- 3.10:
- 3.11:
- 3.12:

2024-02-08 11:02 UTC, nerpaula commented on site/content/3.12/data-science/adapters/arangodb-networkx-adapter.md
> +of the following reasons:
@aMahanna WDYT?

2024-02-09 09:27 UTC, Simran-B requested changes

2024-02-09 09:27 UTC, Simran-B commented on site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
> +
```suggestion
- All `arangodb_pregel_*` metrics
- The `pregel` log topic

```

2024-02-09 09:27 UTC, Simran-B commented on site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
> +The HTTP API for Pregel has been removed in v3.12.0 and is no longer supported.
```suggestion
The `/_api/control_pregel/*` endpoints have been removed in v3.12.0 as Pregel graph processing
is no longer supported. The `arangodb_pregel_*` metrics and the `pregel` log topic have been
 removed as well.
```

2024-02-13 10:17 UTC, Simran-B approved these changes

2024-02-14 04:14 UTC, merged