BTS-666 | Java driver: Add remarks about VelocyStream removal in 3.12
arangodb/docs-hugo pull request #482
Opened 2024-02-26 18:41 UTC by Simran-B

### Description

#### Upstream PRs

- 3.10:
- 3.11:
- 3.12:

2024-02-26 18:42 UTC, Simran-B commented on site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
@rashtao I switched it around to show the most meaningful combination, which I assume is VPack over HTTP

2024-02-27 09:19 UTC, rashtao requested changes

2024-02-27 09:19 UTC, rashtao commented on site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
:+1:

2024-02-27 09:19 UTC, rashtao commented on site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
> +                <artifactId>vst-protocol</artifactId>
This is about excluding the HTTP protocol module, so it should be:
```suggestion
                <artifactId>http-protocol</artifactId>
```

2024-02-27 09:19 UTC, rashtao commented on site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
> +        <artifactId>http-protocol</artifactId>
This is about importing the VST protocol module, so it should be:
```suggestion
        <artifactId>vst-protocol</artifactId>
```

2024-02-27 10:56 UTC, naushniki approved these changes

2024-02-27 11:34 UTC, rashtao requested changes

2024-02-27 11:34 UTC, rashtao commented on site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
>      </dependency>
`http-protocol` is transitively imported, no need to re-add it here:
```suggestion
```

2024-02-27 11:34 UTC, rashtao commented on site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
>  - `com.arangodb:http-protocol` and
`http-protocol` is transitively imported, no need to re-add it here:
```suggestion
```

2024-02-27 11:34 UTC, rashtao commented on site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
> +- `com.arangodb:vst-protocol` and
`vst-protocol` is not imported, so no exclusion is needed:
```suggestion
```

2024-02-27 11:34 UTC, rashtao commented on site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md
>              </exclusion>
`vst-protocol` is not imported, so no exclusion is needed:
```suggestion
```

2024-02-29 21:34 UTC, Simran-B commented
@rashtao Is this good to go now?
https://github.com/arangodb/docs-hugo/blob/2c5dd516f71a7a74148fadf778c1810cf5fe02f6/site/content/3.12/develop/drivers/java/reference-version-7/changes-in-version-7.md#modules

2024-03-01 11:33 UTC, rashtao approved these changes

2024-03-01 18:38 UTC, merged