DOC-440 | Add interface examples for APIs and GUI
arangodb/docs-hugo pull request #648
Opened 2024-12-04 15:08 UTC by Simran-B

### Description

- [x] Databases
- [x] Collections
- [x] Views
- [ ] Documents

#### Upstream PRs

- 3.10: 
- 3.11: 
- 3.12: arangodb/enterprise:3.12.3
- 3.13:

2024-12-04 15:23 UTC, Simran-B commented
/generate

2024-12-09 13:15 UTC, Simran-B commented
/generate

2025-01-15 15:51 UTC, rashtao requested changes

2025-01-15 15:51 UTC, rashtao commented on site/content/3.12/concepts/data-structure/documents/_index.md
> +]);
```suggestion
ArangoCollection coll = db.collection("coll");

// Single document
BaseDocument doc = new BaseDocument("the-document-key");
doc.addAttribute("name", "ArangoDB");
doc.addAttribute("tags", List.of("graph", "database", "NoSQL"));
doc.addAttribute("scalable", true);
doc.addAttribute("company", Map.of(
        "name", "ArangoDB Inc.",
        "founded", 2015
));
doc.addAttribute("name", "ArangoDB");
coll.insertDocument(doc);

// Multiple documents
coll.insertDocuments(List.of(
        new BaseDocument("one"),
        new BaseDocument("two"),
        new BaseDocument("three")
));
```

2025-01-15 15:51 UTC, rashtao commented on site/content/3.12/concepts/data-structure/documents/_index.md
> +}
```suggestion
MultiDocumentEntity<BaseDocument> docs = coll.getDocuments(List.of("one", "two", "three"), BaseDocument.class);
```

2025-01-15 15:51 UTC, rashtao commented on site/content/3.12/concepts/data-structure/documents/_index.md
> +}
```suggestion
// Single document
BaseDocument doc = new BaseDocument("the-document-key");
doc.addAttribute("logo", "avocado");
DocumentUpdateEntity<BaseDocument> result = coll.updateDocument(
        "the-document-key",
        doc,
        new DocumentUpdateOptions().returnNew(true),
        BaseDocument.class
);

// Multiple documents
BaseDocument doc1 = new BaseDocument("one");
doc1.addAttribute("val", 1);
BaseDocument doc2 = new BaseDocument("two");
doc2.addAttribute("val", 2);
BaseDocument doc3 = new BaseDocument("three");
doc3.addAttribute("val", 3);
MultiDocumentEntity<DocumentUpdateEntity<Void>> updatedDocs =
        coll.updateDocuments(List.of(doc1, doc2, doc3));
```

2025-01-15 15:51 UTC, rashtao commented on site/content/3.12/concepts/data-structure/documents/_index.md
> +}
```suggestion
// Single document
BaseDocument doc = new BaseDocument("the-document-key");
doc.addAttribute("logo", "avocado");
DocumentUpdateEntity<BaseDocument> result = coll.replaceDocument(
        "the-document-key",
        doc,
        new DocumentReplaceOptions().returnNew(true),
        BaseDocument.class
);

// Multiple documents
BaseDocument doc1 = new BaseDocument("one");
doc1.addAttribute("val", 1);
BaseDocument doc2 = new BaseDocument("two");
doc2.addAttribute("val", 2);
BaseDocument doc3 = new BaseDocument("three");
doc3.addAttribute("val", 3);
MultiDocumentEntity<DocumentUpdateEntity<Void>> replacedDocs =
        coll.replaceDocuments(List.of(doc1, doc2, doc3));
```

2025-01-15 15:51 UTC, rashtao commented on site/content/3.12/concepts/data-structure/documents/_index.md
> +}
```suggestion
// Single document
DocumentDeleteEntity<Void> result = coll.deleteDocument("the-document-key");

// Multiple documents
MultiDocumentEntity<DocumentDeleteEntity<Void>> multipleResult = 
        coll.deleteDocuments(List.of("one", "two", "three"));
```

2025-01-15 15:51 UTC, rashtao commented on site/content/3.12/concepts/data-structure/documents/schema-validation.md
> +CollectionPropertiesEntity = coll.changeProperties(props);
```suggestion
String schemaRule = (
        "{" +
                "  \"type\": \"object\"," +
                "  \"properties\": {" +
                "    \"nums\": {" +
                "      \"type\": \"array\"," +
                "      \"items\": {" +
                "        \"type\": \"number\"," +
                "        \"minimum\": 6" +
                "      }" +
                "    }" +
                "  }," +
                "  \"additionalProperties\": { \"type\": \"string\" }," +
                "  \"required\": [\"nums\"]" +
                "}");

CollectionPropertiesOptions props = new CollectionPropertiesOptions()
        .schema(new CollectionSchema()
                .setRule(schemaRule)
                .setLevel(CollectionSchema.Level.MODERATE)
                .setMessage("The document does not contain an array of numbers in attribute \"nums\", one of the numbers is greater than 6, or another top-level attribute is not a string.")
        );

ArangoCollection coll = db.collection("coll");
CollectionPropertiesEntity changedProperties = coll.changeProperties(props);
```

2025-01-15 15:51 UTC, rashtao commented on site/content/3.12/concepts/data-structure/views.md
> +SearchAlias viewAlias = db.searchAlias("mySearchAliasView");
```suggestion
ViewEntity view = db.view("myView").getInfo();

ViewEntity viewSearch = db.arangoSearch("myArangoSearchView").getInfo();
ViewEntity viewAlias = db.searchAlias("mySearchAliasView").getInfo();
```

2025-01-15 15:51 UTC, rashtao commented on site/content/3.12/concepts/data-structure/views.md
> +SearchAliasPropertiesEntity viewAlias.getProperties();
```suggestion
ArangoSearch viewSearch = db.arangoSearch("myArangoSearchView");
ArangoSearchPropertiesEntity viewSearchProperties = viewSearch.getProperties();

SearchAlias viewAlias = db.searchAlias("mySearchAliasView");
SearchAliasPropertiesEntity viewAliasProperties = viewAlias.getProperties();
```

2025-01-15 15:51 UTC, rashtao commented on site/content/3.12/concepts/data-structure/views.md
> +);
```suggestion
ArangoSearch viewSearch = db.arangoSearch("myArangoSearchView");
ArangoSearchPropertiesEntity viewSearchProperties = viewSearch.updateProperties(
        new ArangoSearchPropertiesOptions()
                .cleanupIntervalStep(12L)
                .link(CollectionLink.on("coll")
                        .includeAllFields(true)
                )
);

SearchAlias viewAlias = db.searchAlias("mySearchAliasView");
SearchAliasPropertiesEntity viewAliasProperties = viewAlias.updateProperties(
        new SearchAliasPropertiesOptions()
                .indexes(new SearchAliasIndex("coll", "idx"))
);
```

2025-01-20 21:43 UTC, Simran-B commented on site/content/3.12/concepts/data-structure/documents/computed-values.md
> +    .computeOn(ComputeOn.insert, ComputeOn.update, ComputeOn.replace)
@rashtao I added the examples for Computed Values now too.
Is it necessary to use `ComputedValue.ComputeOn.*` here to refer to the elements of the enum?

2025-01-21 02:55 UTC, aMahanna requested changes
Python examples look good,2 small adjustments:

2025-01-21 02:55 UTC, aMahanna commented on site/content/3.12/concepts/data-structure/documents/computed-values.md
> +  computed_values: [
```suggestion
  computed_values=[
```

2025-01-21 02:55 UTC, aMahanna commented on site/content/3.12/concepts/data-structure/documents/_index.md
> +coll = db.get_collection("coll")
```suggestion
coll = db.collection("coll")
```

2025-01-21 10:05 UTC, rashtao commented on site/content/3.12/concepts/data-structure/documents/computed-values.md
> +    .computeOn(ComputeOn.insert, ComputeOn.update, ComputeOn.replace)
```suggestion
    .computeOn(ComputedValue.ComputeOn.insert, ComputedValue.ComputeOn.update, ComputedValue.ComputeOn.replace)
```

2025-01-22 15:02 UTC, Simran-B commented on site/content/3.12/concepts/data-structure/views.md
> +SearchAlias viewAlias = db.searchAlias("mySearchAliasView");
```suggestion
ArangoView view = db.view("myView");
ViewEntity viewInfo = view.getInfo();

ArangoSearch viewSearch = db.arangoSearch("myArangoSearchView");
ViewEntity viewSearchInfo = viewSearch.getInfo();

SearchAlias viewAlias = db.searchAlias("mySearchAliasView");
ViewEntity viewAliasInfo = viewAlias.getInfo();
```

2025-04-02 03:03 UTC, Simran-B commented
/generate

2025-04-25 14:46 UTC, Simran-B commented
/generate-commit

2025-04-25 15:10 UTC, merged